import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Rick And Morty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className=" z-0 h-full  bg-cover bg-center bg-no-repeat "
        style={{ backgroundImage: "url('/assets/background.jpg')" }}
      >
        <div className="absolute inset-0 bg-black/50 z-0 pointer-events-none" />
        <main className="relative z-20">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
